
root@mysqldb 18:05:  [(none)]> select * from performance_schema.threads;
+-----------+----------------------------------------+------------+----------------+------------------+------------------+----------------+---------------------+------------------+-------------------+------------------------------------------+------------------+------+--------------+---------+-----------------+--------------+
| THREAD_ID | NAME                                   | TYPE       | PROCESSLIST_ID | PROCESSLIST_USER | PROCESSLIST_HOST | PROCESSLIST_DB | PROCESSLIST_COMMAND | PROCESSLIST_TIME | PROCESSLIST_STATE | PROCESSLIST_INFO                         | PARENT_THREAD_ID | ROLE | INSTRUMENTED | HISTORY | CONNECTION_TYPE | THREAD_OS_ID |
+-----------+----------------------------------------+------------+----------------+------------------+------------------+----------------+---------------------+------------------+-------------------+------------------------------------------+------------------+------+--------------+---------+-----------------+--------------+
|         1 | thread/sql/main                        | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |           457323 | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12496 |
|         2 | thread/sql/thread_timer_notifier       | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |                1 | NULL | YES          | YES     | NULL            |        12497 |
|         3 | thread/innodb/io_ibuf_thread           | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12498 |
|         4 | thread/innodb/io_log_thread            | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12499 |
|         5 | thread/innodb/io_read_thread           | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12501 |
|         6 | thread/innodb/io_read_thread           | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12500 |
|         7 | thread/innodb/io_read_thread           | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12502 |
|         8 | thread/innodb/io_read_thread           | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12503 |
|         9 | thread/innodb/io_read_thread           | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12504 |
|        10 | thread/innodb/io_read_thread           | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12505 |
|        11 | thread/innodb/io_read_thread           | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12506 |
|        12 | thread/innodb/io_read_thread           | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12507 |
|        13 | thread/innodb/io_write_thread          | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12509 |
|        14 | thread/innodb/io_write_thread          | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12508 |
|        15 | thread/innodb/io_write_thread          | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12510 |
|        16 | thread/innodb/io_write_thread          | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12511 |
|        17 | thread/innodb/io_write_thread          | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12512 |
|        18 | thread/innodb/io_write_thread          | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12513 |
|        19 | thread/innodb/io_write_thread          | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12514 |
|        20 | thread/innodb/io_write_thread          | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12515 |
|        21 | thread/innodb/page_cleaner_thread      | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12516 |
|        23 | thread/innodb/srv_lock_timeout_thread  | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12521 |
|        24 | thread/innodb/srv_monitor_thread       | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12523 |
|        25 | thread/innodb/srv_error_monitor_thread | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12522 |
|        26 | thread/innodb/srv_master_thread        | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12524 |
|        27 | thread/innodb/srv_worker_thread        | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12527 |
|        28 | thread/innodb/srv_purge_thread         | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12525 |
|        29 | thread/innodb/srv_worker_thread        | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12528 |
|        30 | thread/innodb/srv_worker_thread        | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12526 |
|        31 | thread/innodb/buf_dump_thread          | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12531 |
|        32 | thread/innodb/dict_stats_thread        | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |             NULL | NULL | YES          | YES     | NULL            |        12532 |
|        33 | thread/sql/signal_handler              | BACKGROUND |           NULL | NULL             | NULL             | NULL           | NULL                |             NULL | NULL              | NULL                                     |                1 | NULL | YES          | YES     | NULL            |        12537 |
|        34 | thread/sql/compress_gtid_table         | FOREGROUND |              1 | NULL             | NULL             | NULL           | Daemon              |           457323 | Suspending        | NULL                                     |                1 | NULL | YES          | YES     | NULL            |        12538 |
|        49 | thread/sql/one_connection              | FOREGROUND |             16 | root             | localhost        | sys            | Query               |                0 | Sending data      | select * from performance_schema.threads |             NULL | NULL | YES          | YES     | Socket          |        13506 |
+-----------+----------------------------------------+------------+----------------+------------------+------------------+----------------+---------------------+------------------+-------------------+------------------------------------------+------------------+------+--------------+---------+-----------------+--------------+
34 rows in set (0.01 sec)
