mysql> mysql> show relaylog events in 'localhost-relay-bin.000005';
+----------------------------+------+----------------+-----------+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Log_name                   | Pos  | Event_type     | Server_id | End_log_pos | Info                                                                                                                                                                                                                |
+----------------------------+------+----------------+-----------+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| localhost-relay-bin.000005 |    4 | Format_desc    |   3306202 |         123 | Server ver: 5.7.22-log, Binlog ver: 4                                                                                                                                                                               |
| localhost-relay-bin.000005 |  123 | Previous_gtids |   3306202 |         154 |                                                                                                                                                                                                                     |
| localhost-relay-bin.000005 |  154 | Rotate         |    330607 |           0 | mysql-bin.000003;pos=4                                                                                                                                                                                              |
| localhost-relay-bin.000005 |  201 | Format_desc    |    330607 |         123 | Server ver: 5.7.22-log, Binlog ver: 4                                                                                                                                                                               |
| localhost-relay-bin.000005 |  320 | Rotate         |         0 |         367 | mysql-bin.000003;pos=154                                                                                                                                                                                            |
| localhost-relay-bin.000005 |  367 | Anonymous_Gtid |    330607 |         219 | SET @@SESSION.GTID_NEXT= 'ANONYMOUS'                                                                                                                                                                                |
| localhost-relay-bin.000005 |  432 | Query          |    330607 |         448 | GRANT REPLICATION SLAVE ON *.* TO 'rpl'@'192.168.0.202' IDENTIFIED WITH 'mysql_native_password' AS '*3C76A04FE84B30367B4DBEAD39C53842FB508A39'                                                                      |
| localhost-relay-bin.000005 |  661 | Anonymous_Gtid |    330607 |         513 | SET @@SESSION.GTID_NEXT= 'ANONYMOUS'                                                                                                                                                                                |
| localhost-relay-bin.000005 |  726 | Query          |    330607 |         641 | create  database test_db DEFAULT CHARSET utf8mb4                                                                                                                                                                    |
| localhost-relay-bin.000005 |  854 | Anonymous_Gtid |    330607 |         706 | SET @@SESSION.GTID_NEXT= 'ANONYMOUS'                                                                                                                                                                                |
| localhost-relay-bin.000005 |  919 | Query          |    330607 |         982 | use `test_db`; CREATE TABLE `t` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `c` int(11) DEFAULT NULL,
  `d` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `c` (`c`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 |
| localhost-relay-bin.000005 | 1195 | Anonymous_Gtid |    330607 |        1047 | SET @@SESSION.GTID_NEXT= 'ANONYMOUS'                                                                                                                                                                                |
| localhost-relay-bin.000005 | 1260 | Query          |    330607 |        1122 | BEGIN                                                                                                                                                                                                               |
| localhost-relay-bin.000005 | 1335 | Table_map      |    330607 |        1171 | table_id: 108 (test_db.t)                                                                                                                                                                                           |
| localhost-relay-bin.000005 | 1384 | Write_rows     |    330607 |        1223 | table_id: 108 flags: STMT_END_F                                                                                                                                                                                     |
| localhost-relay-bin.000005 | 1436 | Xid            |    330607 |        1254 | COMMIT /* xid=39 */                                                                                                                                                                                                 |
| localhost-relay-bin.000005 | 1467 | Anonymous_Gtid |    330607 |        1319 | SET @@SESSION.GTID_NEXT= 'ANONYMOUS'                                                                                                                                                                                |
| localhost-relay-bin.000005 | 1532 | Query          |    330607 |        1394 | BEGIN                                                                                                                                                                                                               |
| localhost-relay-bin.000005 | 1607 | Table_map      |    330607 |        1443 | table_id: 108 (test_db.t)                                                                                                                                                                                           |
| localhost-relay-bin.000005 | 1656 | Write_rows     |    330607 |        1495 | table_id: 108 flags: STMT_END_F                                                                                                                                                                                     |
| localhost-relay-bin.000005 | 1708 | Xid            |    330607 |        1526 | COMMIT /* xid=40 */                                                                                                                                                                                                 |
| localhost-relay-bin.000005 | 1739 | Anonymous_Gtid |    330607 |        1591 | SET @@SESSION.GTID_NEXT= 'ANONYMOUS'                                                                                                                                                                                |
| localhost-relay-bin.000005 | 1804 | Query          |    330607 |        1666 | BEGIN                                                                                                                                                                                                               |
| localhost-relay-bin.000005 | 1879 | Table_map      |    330607 |        1715 | table_id: 108 (test_db.t)                                                                                                                                                                                           |
| localhost-relay-bin.000005 | 1928 | Write_rows     |    330607 |        1767 | table_id: 108 flags: STMT_END_F                                                                                                                                                                                     |
| localhost-relay-bin.000005 | 1980 | Xid            |    330607 |        1798 | COMMIT /* xid=41 */                                                                                                                                                                                                 |
| localhost-relay-bin.000005 | 2011 | Anonymous_Gtid |    330607 |        1863 | SET @@SESSION.GTID_NEXT= 'ANONYMOUS'                                                                                                                                                                                |
| localhost-relay-bin.000005 | 2076 | Query          |    330607 |        1938 | BEGIN                                                                                                                                                                                                               |
| localhost-relay-bin.000005 | 2151 | Table_map      |    330607 |        1987 | table_id: 108 (test_db.t)                                                                                                                                                                                           |
| localhost-relay-bin.000005 | 2200 | Write_rows     |    330607 |        2039 | table_id: 108 flags: STMT_END_F                                                                                                                                                                                     |
| localhost-relay-bin.000005 | 2252 | Xid            |    330607 |        2070 | COMMIT /* xid=42 */                                                                                                                                                                                                 |
| localhost-relay-bin.000005 | 2283 | Anonymous_Gtid |    330607 |        2135 | SET @@SESSION.GTID_NEXT= 'ANONYMOUS'                                                                                                                                                                                |
| localhost-relay-bin.000005 | 2348 | Query          |    330607 |        2210 | BEGIN                                                                                                                                                                                                               |
| localhost-relay-bin.000005 | 2423 | Table_map      |    330607 |        2259 | table_id: 108 (test_db.t)                                                                                                                                                                                           |
| localhost-relay-bin.000005 | 2472 | Write_rows     |    330607 |        2311 | table_id: 108 flags: STMT_END_F                                                                                                                                                                                     |
| localhost-relay-bin.000005 | 2524 | Xid            |    330607 |        2342 | COMMIT /* xid=43 */                                                                                                                                                                                                 |
| localhost-relay-bin.000005 | 2555 | Anonymous_Gtid |    330607 |        2407 | SET @@SESSION.GTID_NEXT= 'ANONYMOUS'                                                                                                                                                                                |
| localhost-relay-bin.000005 | 2620 | Query          |    330607 |        2482 | BEGIN                                                                                                                                                                                                               |
| localhost-relay-bin.000005 | 2695 | Table_map      |    330607 |        2531 | table_id: 108 (test_db.t)                                                                                                                                                                                           |
| localhost-relay-bin.000005 | 2744 | Write_rows     |    330607 |        2583 | table_id: 108 flags: STMT_END_F                                                                                                                                                                                     |
| localhost-relay-bin.000005 | 2796 | Xid            |    330607 |        2614 | COMMIT /* xid=47 */                                                                                                                                                                                                 |
| localhost-relay-bin.000005 | 2827 | Rotate         |   3306202 |        2884 | localhost-relay-bin.000006;pos=4                                                                                                                                                                                    |
+----------------------------+------+----------------+-----------+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
42 rows in set (0.00 sec)
