
mysql> select version();
+------------+
| version()  |
+------------+
| 5.7.22-log |
+------------+
1 row in set (0.00 sec)


mysql> show global variables like '%innodb_checksum%';
+---------------------------+-------+
| Variable_name             | Value |
+---------------------------+-------+
| innodb_checksum_algorithm | crc32 |
| innodb_checksums          | ON    |
+---------------------------+-------+
2 rows in set (0.00 sec)





innodb_checksums

	该参数用于开启或者关闭对这个页完整性的检查。默认情况下启用此验证。
	
	InnoDB 可以对从磁盘读取的所有表空间页面使用校验和验证，以确保针对硬件故障或损坏的数据文件提供额外的容错能力。 
	
	InnoDB 每次从磁盘读取一个页就会检测该页的完整性，如果发现不同，则会导致MySQL crash。
					
					
	
	
innodb_checksum_algorithm

	数据页的checksum值的计算方法依赖参数innodb_checksum_algorithm。
	
	在 MySQL 5.7.7 之前

		innodb_checksums=ON is the same as innodb_checksum_algorithm=innodb.
		innodb_checksums=OFF is the same as innodb_checksum_algorithm=none.
	
	
	
	从 MySQL 5.7.7 开始
	
		innodb_checksum_algorithm 默认值为 crc32
		innodb_checksums=ON 与 innodb_checksum_algorithm=crc32 相同。
		innodb_checksums=OFF 与 innodb_checksum_algorithm=none 相同。




	Value				Generated checksum (when writing)														Permitted checksums (when reading)
	none				A constant number.																		Any of the checksums generated by none, innodb, or crc32.
	innodb				A checksum calculated in software, using the original algorithm from InnoDB.			Any of the checksums generated by none, innodb, or crc32.
	crc32				A checksum calculated using the crc32 algorithm, possibly done with a hardware assist.	Any of the checksums generated by none, innodb, or crc32.
	strict_none			A constant number																		Any of the checksums generated by none, innodb, or crc32. InnoDB prints an error message if a valid but non-matching checksum is encountered.
	strict_innodb		A checksum calculated in software, using the original algorithm from InnoDB.			Any of the checksums generated by none, innodb, or crc32. InnoDB prints an error message if a valid but non-matching checksum is encountered.
	strict_crc32		A checksum calculated using the crc32 algorithm, possibly done with a hardware assist.	Any of the checksums generated by none, innodb, or crc32. InnoDB prints an error message if a valid but non-matching checksum is encountered.

	
	
	目前提供四种计算checksum的方法：
		第一种是crc32校验(buf_calc_page_crc32)，这种是一种比较新的计算方法，但是可以使用cpu硬件指令来加速。
		第二种是innodb校验，是innodb自己开发的一种计算方法，但是有新老两种变体，两种变体计算结果不同，为了兼容老的变体，需要在代码中兼容。
		第三种是none模式，这种计算方式不计算每个数据页的校验值，而是使用一个指定的值填充checksum字段，这种方式速度很快，但也保证不了数据的正确性。
		
		第四种是 strict(严格模式) 开头的
		
			strict的选项表示，在读取的时候必须是指定的校验方式的校验值才通过，其他的都不行。
			-- 也就是说对数据页做读取和存储的时候，两者的计算checksum的方式是一样的才可以通过。
			举例：
				指定了strict_crc32，那么在数据页被读取计算checksum时候，对应的校验值必须也是crc32的才可通过
				但是如果指定crc32，如果存储的是innodb或者none的结果，也是可以通过校验的。
				
			之所以提供了这种选项，就是为了兼容老版本的mysql以及防止校验算法被修改而导致的数据不可用。
			这里提醒一下，使用strict模式由于计算量比较小，因此效率相对较高。
			
		https://www.cnblogs.com/coderyuhui/p/8884717.html
		
		
相关参考
	
	https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_checksums
	https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_checksum_algorithm
	
	
	
	