

DROP TEMPORARY TABLE IF EXISTS t2;
 
CREATE TEMPORARY TABLE t2(  
	Id INT UNSIGNED  NOT NULL  AUTO_INCREMENT PRIMARY KEY,
	nClubId INT DEFAULT 0
);

b buf_LRU_flush_or_remove_pages

DROP TEMPORARY TABLE IF EXISTS t2;

