/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 4
#200320 17:55:37 server id 303306  end_log_pos 123 CRC32 0x4da3f26d 	Start: binlog v 4, server v 5.7.19-log created 200320 17:55:37
# This Format_description_event appears in a relay log and was generated by the slave thread.
# at 123
#200320 17:55:37 server id 303306  end_log_pos 154 CRC32 0x6b5d0db7 	Previous-GTIDs
# [empty]
# at 154
#700101  8:00:00 server id 273306  end_log_pos 0 CRC32 0x19db59ea 	Rotate to mysql-bin.000007  pos: 4
# at 201
#200320 16:05:40 server id 273306  end_log_pos 123 CRC32 0x55a967b8 	Start: binlog v 4, server v 5.7.19-log created 200320 16:05:40
# at 320
#200320 17:55:37 server id 0  end_log_pos 367 CRC32 0xb2b1c379 	Rotate to mysql-bin.000007  pos: 194
# at 367
#200320 17:55:37 server id 0  end_log_pos 414 CRC32 0x94f4ab6d 	Rotate to mysql-bin.000007  pos: 1385
# at 414
#200320 17:40:34 server id 273306  end_log_pos 1450 CRC32 0x15efb4e4 	GTID	last_committed=4	sequence_number=5	rbr_only=no
SET @@SESSION.GTID_NEXT= 'f7323d17-6442-11ea-8a77-080027758761:110654'/*!*/;
# at 479
#200320 17:40:34 server id 273306  end_log_pos 1781 CRC32 0x2cb63957 	Query	thread_id=39	exec_time=0	error_code=0
use `db1`/*!*/;
SET TIMESTAMP=1584697234/*!*/;
SET @@session.pseudo_thread_id=39/*!*/;
SET @@session.foreign_key_checks=1, @@session.sql_auto_is_null=0, @@session.unique_checks=1, @@session.autocommit=1/*!*/;
SET @@session.sql_mode=1436549152/*!*/;
SET @@session.auto_increment_increment=1, @@session.auto_increment_offset=1/*!*/;
/*!\C utf8 *//*!*/;
SET @@session.character_set_client=33,@@session.collation_connection=33,@@session.collation_server=33/*!*/;
SET @@session.lc_time_names=0/*!*/;
SET @@session.collation_database=DEFAULT/*!*/;
CREATE TABLE `t2` (
	  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键Id',
	  `name` varchar(20) DEFAULT NULL,
	  `amount` int(11) DEFAULT NULL,
	  PRIMARY KEY (`id`),
	  KEY `idx_name` (`name`)
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4
/*!*/;
# at 810
#200320 17:40:34 server id 273306  end_log_pos 1846 CRC32 0x978934bd 	GTID	last_committed=5	sequence_number=6	rbr_only=yes
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
SET @@SESSION.GTID_NEXT= 'f7323d17-6442-11ea-8a77-080027758761:110655'/*!*/;
# at 875
#200320 17:40:34 server id 273306  end_log_pos 1917 CRC32 0xc8349001 	Query	thread_id=39	exec_time=0	error_code=0
SET TIMESTAMP=1584697234/*!*/;
BEGIN
/*!*/;
# at 946
#200320 17:40:34 server id 273306  end_log_pos 1965 CRC32 0x00690820 	Table_map: `db1`.`t2` mapped to number 409
# at 994
#200320 17:40:34 server id 273306  end_log_pos 2015 CRC32 0x9c0d0404 	Write_rows: table id 409 flags: STMT_END_F
### INSERT INTO `db1`.`t2`
### SET
###   @1=1 /* LONGINT meta=0 nullable=0 is_null=0 */
###   @2='1' /* VARSTRING(80) meta=80 nullable=1 is_null=0 */
###   @3=2 /* INT meta=0 nullable=1 is_null=0 */
# at 1044
#200320 17:40:34 server id 273306  end_log_pos 2046 CRC32 0x4e159f4e 	Xid = 247
COMMIT/*!*/;
# at 1075
#200320 17:40:34 server id 273306  end_log_pos 2111 CRC32 0xf0dff028 	GTID	last_committed=6	sequence_number=7	rbr_only=yes
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
SET @@SESSION.GTID_NEXT= 'f7323d17-6442-11ea-8a77-080027758761:110656'/*!*/;
# at 1140
#200320 17:40:34 server id 273306  end_log_pos 2182 CRC32 0xb1fba547 	Query	thread_id=39	exec_time=0	error_code=0
SET TIMESTAMP=1584697234/*!*/;
BEGIN
/*!*/;
# at 1211
#200320 17:40:34 server id 273306  end_log_pos 2230 CRC32 0x07544df2 	Table_map: `db1`.`t2` mapped to number 409
# at 1259
#200320 17:40:34 server id 273306  end_log_pos 2280 CRC32 0x8a1cf750 	Write_rows: table id 409 flags: STMT_END_F
### INSERT INTO `db1`.`t2`
### SET
###   @1=2 /* LONGINT meta=0 nullable=0 is_null=0 */
###   @2='1' /* VARSTRING(80) meta=80 nullable=1 is_null=0 */
###   @3=2 /* INT meta=0 nullable=1 is_null=0 */
# at 1309
#200320 17:40:34 server id 273306  end_log_pos 2311 CRC32 0xaa9922b5 	Xid = 248
COMMIT/*!*/;
# at 1340
#200320 17:40:34 server id 273306  end_log_pos 2376 CRC32 0x21f72ee5 	GTID	last_committed=7	sequence_number=8	rbr_only=yes
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
SET @@SESSION.GTID_NEXT= 'f7323d17-6442-11ea-8a77-080027758761:110657'/*!*/;
# at 1405
#200320 17:40:34 server id 273306  end_log_pos 2447 CRC32 0xc3abf100 	Query	thread_id=39	exec_time=0	error_code=0
SET TIMESTAMP=1584697234/*!*/;
BEGIN
/*!*/;
# at 1476
#200320 17:40:34 server id 273306  end_log_pos 2495 CRC32 0x42ec00a3 	Table_map: `db1`.`t2` mapped to number 409
# at 1524
#200320 17:40:34 server id 273306  end_log_pos 2545 CRC32 0x65150114 	Write_rows: table id 409 flags: STMT_END_F
### INSERT INTO `db1`.`t2`
### SET
###   @1=3 /* LONGINT meta=0 nullable=0 is_null=0 */
###   @2='1' /* VARSTRING(80) meta=80 nullable=1 is_null=0 */
###   @3=2 /* INT meta=0 nullable=1 is_null=0 */
# at 1574
#200320 17:40:34 server id 273306  end_log_pos 2576 CRC32 0xd886d849 	Xid = 249
COMMIT/*!*/;
# at 1605
#200320 17:40:34 server id 273306  end_log_pos 2641 CRC32 0x8b62af82 	GTID	last_committed=8	sequence_number=9	rbr_only=yes
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
SET @@SESSION.GTID_NEXT= 'f7323d17-6442-11ea-8a77-080027758761:110658'/*!*/;
# at 1670
#200320 17:40:34 server id 273306  end_log_pos 2712 CRC32 0x5ee0e6a1 	Query	thread_id=39	exec_time=0	error_code=0
SET TIMESTAMP=1584697234/*!*/;
BEGIN
/*!*/;
# at 1741
#200320 17:40:34 server id 273306  end_log_pos 2760 CRC32 0xc810163f 	Table_map: `db1`.`t2` mapped to number 409
# at 1789
#200320 17:40:34 server id 273306  end_log_pos 2810 CRC32 0xfe3593a7 	Write_rows: table id 409 flags: STMT_END_F
### INSERT INTO `db1`.`t2`
### SET
###   @1=4 /* LONGINT meta=0 nullable=0 is_null=0 */
###   @2='1' /* VARSTRING(80) meta=80 nullable=1 is_null=0 */
###   @3=2 /* INT meta=0 nullable=1 is_null=0 */
# at 1839
#200320 17:40:34 server id 273306  end_log_pos 2841 CRC32 0x25c9f96f 	Xid = 250
COMMIT/*!*/;
# at 1870
#200320 17:40:34 server id 273306  end_log_pos 2906 CRC32 0x175bf75e 	GTID	last_committed=9	sequence_number=10	rbr_only=yes
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
SET @@SESSION.GTID_NEXT= 'f7323d17-6442-11ea-8a77-080027758761:110659'/*!*/;
# at 1935
#200320 17:40:34 server id 273306  end_log_pos 2977 CRC32 0x025f1f46 	Query	thread_id=39	exec_time=0	error_code=0
SET TIMESTAMP=1584697234/*!*/;
BEGIN
/*!*/;
# at 2006
#200320 17:40:34 server id 273306  end_log_pos 3025 CRC32 0xbd0cdb2e 	Table_map: `db1`.`t1` mapped to number 410
# at 2054
#200320 17:40:34 server id 273306  end_log_pos 3075 CRC32 0x46f6ba79 	Write_rows: table id 410 flags: STMT_END_F
### INSERT INTO `db1`.`t1`
### SET
###   @1=4 /* LONGINT meta=0 nullable=0 is_null=0 */
###   @2='1' /* VARSTRING(80) meta=80 nullable=1 is_null=0 */
###   @3=2 /* INT meta=0 nullable=1 is_null=0 */
# at 2104
#200320 17:40:34 server id 273306  end_log_pos 3106 CRC32 0x70fe80f0 	Xid = 251
COMMIT/*!*/;
# at 2135
#200320 17:41:39 server id 273306  end_log_pos 3171 CRC32 0x3119ae99 	GTID	last_committed=10	sequence_number=11	rbr_only=no
SET @@SESSION.GTID_NEXT= 'f7323d17-6442-11ea-8a77-080027758761:110660'/*!*/;
# at 2200
#200320 17:41:39 server id 273306  end_log_pos 3284 CRC32 0x91212cb0 	Query	thread_id=39	exec_time=0	error_code=0
SET TIMESTAMP=1584697299/*!*/;
DROP TABLE `t1` /* generated by server */
/*!*/;
# at 2313
#200320 17:41:39 server id 273306  end_log_pos 3349 CRC32 0xaf5c03d3 	GTID	last_committed=11	sequence_number=12	rbr_only=yes
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
SET @@SESSION.GTID_NEXT= 'f7323d17-6442-11ea-8a77-080027758761:110661'/*!*/;
# at 2378
#200320 17:41:39 server id 273306  end_log_pos 3420 CRC32 0x44edacd0 	Query	thread_id=39	exec_time=0	error_code=0
SET TIMESTAMP=1584697299/*!*/;
BEGIN
/*!*/;
# at 2449
#200320 17:41:39 server id 273306  end_log_pos 3468 CRC32 0xe93d23ed 	Table_map: `db1`.`t2` mapped to number 409
# at 2497
#200320 17:41:39 server id 273306  end_log_pos 3518 CRC32 0x86873042 	Write_rows: table id 409 flags: STMT_END_F
### INSERT INTO `db1`.`t2`
### SET
###   @1=5 /* LONGINT meta=0 nullable=0 is_null=0 */
###   @2='1' /* VARSTRING(80) meta=80 nullable=1 is_null=0 */
###   @3=2 /* INT meta=0 nullable=1 is_null=0 */
# at 2547
#200320 17:41:39 server id 273306  end_log_pos 3549 CRC32 0x12590cbc 	Xid = 261
COMMIT/*!*/;
# at 2578
#200320 17:55:37 server id 303306  end_log_pos 2625 CRC32 0xb21724d8 	Rotate to relay-bin.000003  pos: 4
SET @@SESSION.GTID_NEXT= 'AUTOMATIC' /* added by mysqlbinlog */ /*!*/;
DELIMITER ;
# End of log file
/*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;
